name: Deploy Bridge Service To VM

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy-vm-service.yml
    with:
      service_name: bridge-service
      compose_service: bridge_service
      docker_context: ./bridge-service
      dockerfile: ./bridge-service/Dockerfile
    secrets: inherit
