name: Deploy Liquid Swap To VM

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy-vm-service.yml
    with:
      service_name: liquid-swap
      compose_service: liquid_swap_service
      docker_context: .
      dockerfile: ./liquid-swap-service/Dockerfile
    secrets: inherit
